// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DoHttp(arg1:main.AxiosRequestConfig):Promise<main.AxiosResponse>;
